import { z } from "zod";
import { commonValidations } from "@/utils/formUtils";

export const aboutCmsSchema = z.object({
  about_title: commonValidations.requiredString("About Title"),
  about_title_ar: commonValidations.requiredString("About Title (Arabic)"),
  about_description: commonValidations.requiredString("About Description"),
  about_description_ar: commonValidations.requiredString("About Description (Arabic)"),
  media_path: commonValidations.requiredFile("Media"),
  media_alt: commonValidations.requiredString("Alt text"),
  media_alt_ar: commonValidations.requiredString("Alt text (Arabic)"),
  trust_title: commonValidations.requiredString("Trust Title"),
  trust_title_ar: commonValidations.requiredString("Trust Title (Arabic)"),
  trust_description: commonValidations.requiredString("Trust Description"),
  trust_description_ar: commonValidations.requiredString("Trust Description (Arabic)"),
  mission_title: commonValidations.requiredString("Mission Title"),
  mission_title_ar: commonValidations.requiredString("Mission Title (Arabic)"),
  vision_title: commonValidations.requiredString("Vision Title"),
  vision_title_ar: commonValidations.requiredString("Vision Title (Arabic)"),
  mission_description: commonValidations.requiredString("Mission Description"),
  mission_description_ar: commonValidations.requiredString("Mission Description (Arabic)"),
  vision_description: commonValidations.requiredString("Vision Description"),
  vision_description_ar: commonValidations.requiredString("Vision Description (Arabic)"),
  history_title: commonValidations.requiredString("History Title"),
  history_title_ar: commonValidations.requiredString("History Title (Arabic)"),
  message_title: commonValidations.requiredString("Message Title"),
  message_title_ar: commonValidations.requiredString("Message Title (Arabic)"),
  message_subtitle: commonValidations.requiredString("Message Subtitle"),
  message_subtitle_ar: commonValidations.requiredString("Message Subtitle (Arabic)"),
  work_title: commonValidations.requiredString("Work Title"),
  work_title_ar: commonValidations.requiredString("Work Title (Arabic)"),
  about_core_title: commonValidations.requiredString("About Core Title"),
  about_core_title_ar: commonValidations.requiredString("About Core Title (Arabic)"),
  about_code_media_path: commonValidations.requiredFile("About Core Media"),
  about_code_media_alt: commonValidations.requiredString("About Core Media Alt text"),
  about_code_media_alt_ar: commonValidations.requiredString("About Core Media Alt text (Arabic)"),
  features_title: commonValidations.requiredString("Features Title"),
  features_title_ar: commonValidations.requiredString("Features Title (Arabic)"),
  features_sub_title: commonValidations.requiredString("Features Subtitle"),
  features_sub_title_ar: commonValidations.requiredString("Features Subtitle (Arabic)"),
  features_description: commonValidations.requiredString(
    "Features Description",
  ),
  features_description_ar: commonValidations.requiredString("Features Description (Arabic)"),
  industry_title: commonValidations.requiredString("Industry Title"),
  industry_title_ar: commonValidations.requiredString("Industry Title (Arabic)"),
  industry_description: commonValidations.requiredString(
    "Industry Description",
  ),
  industry_description_ar: commonValidations.requiredString("Industry Description (Arabic)"),
  industry_media_path: commonValidations.requiredFile("Industry Media"),
  industry_media_alt: commonValidations.requiredString("Industry Media Alt text"),
  industry_media_alt_ar: commonValidations.requiredString("Industry Media Alt text (Arabic)"),
});

export type AboutCmsFormData = z.infer<typeof aboutCmsSchema>;